NumPy stands for Numerical Python and is the core library for numeric and scientific computing

It basically consist of multi-dimensional array objects and a collection of routines for processing those arrays

In [2]:
import numpy as np
n1 = np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [3]:
n2 = np.array([[10,20,30,40],[60,70,80,90]])
n2

array([[10, 20, 30, 40],
       [60, 70, 80, 90]])

In [4]:
type(n1)

numpy.ndarray

In [5]:
n1.ndim

1

In [6]:
n2.ndim

2

Initializing NumPy array with zeros

In [7]:
z1 = np.zeros((1,2))
z1

array([[0., 0.]])

In [8]:
z2 = np.zeros((5,5))
z2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
o1 = np.ones((4,4))
o1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Initializing NumPy array with same Number

In [10]:
a1 = np.full((2,2),10)
a1

array([[10, 10],
       [10, 10]])

Initializing NumPy array withing a range

In [11]:
r1 = np.arange(10,20)
r1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [12]:
r2 = np.arange(10,60,5)

In [13]:
r2

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

**********************************************************************************

Pandas stands for Panel Data and is the core library for data manipulation and data analysis

It consists of single and muti-dimensional data structures for data manipulation
a. Single Dimensional data structure is called as "Series Object"
b. Multi-dimensional data structure is called as "Data Frames"

Series Object is one-dimensional labeled array

In [14]:
import pandas as pd
s1  = pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [15]:
type(s1)

pandas.core.series.Series

In [16]:
s2 = pd.Series([1,2,3,4,5,6],index=['a','b','c','d','e','f'])
s2

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [17]:
s1[3]

4

In [18]:
s1[-3:]

2    3
3    4
4    5
dtype: int64

In [19]:
s1[:3]

0    1
1    2
2    3
dtype: int64

Dataframe is a 2-dimesional labelled data-structure. Dataframe comprises of rows and columns

In [20]:
pd.DataFrame({"Name":['Bob','Sam','Anne'],"Marks":[76,25,92]})

Name  Marks
0   Bob     76
1   Sam     25
2  Anne     92

In [21]:
d2={"Name":['Bob','Sam','Anne'],"Marks":[76,25,92]}
d2

{'Name': ['Bob', 'Sam', 'Anne'], 'Marks': [76, 25, 92]}

In [22]:
d2.keys()

dict_keys(['Name', 'Marks'])

In [24]:
courses = pd.read_csv('HRApps-Data-Courses.csv')

In [25]:
courses

ID                         Title  \
0   ENG-001       Engineering Orientation   
1   GEN-001           Company orientation   
2   GEN-002           Time Off Management   
3   GEN-003         Benefits Presentation   
4   GEN-004             Insurance Options   
5   GEN-005           Retirement Planning   
6   MGT-001  Conflict Resolution Workshop   
7   MKT-001         Marketing Orientation   
8   SAL-001             Sales Orientation   
9   SAL-002             Effective Selling   
10  GEN-007           Time Off Management   
11  GEN-008         Benefits Presentation   
12  GEN-009             Insurance Options   
13  GEN-006           Retirement Planning   
14  MGT-002  Conflict Resolution Workshop   
15  MKT-002         Marketing Orientation   
16  SAL-003             Sales Orientation   
17  SAL-004             Effective Selling   

                                          Description  Hours   Department  
0   Learn the basic organization of the Engineerin...    2.0  Engineering  
1   Learn about the company's history and corporat...    1.0          All  
2                Review the time off reporting system    0.5          All  
3   Information session on the various company-spo...    1.0          All  
4   Information session on the company-sponsored i...    1.5          All  
5   Information session on the company's retiremen...    2.0          All  
6   Learn effective strategies for resolving confl...    4.0          All  
7   Learn the basic organization of the Marketing ...    2.0    Marketing  
8     Learn the basic organization of the Sales group    2.0        Sales  
9   Sales workshop focusing on effective technique...    2.5        Sales  
10               Review the time off reporting system    0.5          All  
11  Information session on the various company-spo...    1.0          All  
12  Information session on the company-sponsored i...    1.5          All  
13  Information session on the company's retiremen...    2.0          All  
14  Learn effective strategies for resolving confl...    4.0          All  
15  Learn the basic organization of the Marketing ...    2.0    Marketing  
16    Learn the basic organization of the Sales group    2.0        Sales  
17  Sales workshop focusing on effective technique...    2.5        Sales

In [ ]:
courses.head(2)

In [ ]:
courses.tail(3)

In [ ]:
courses.describe()

In [ ]:
courses.shape

In [ ]:
courses.sort_index(ascending=False)

In [ ]:
courses_sorted= courses.sort_values('Title')
courses_sorted.head(17)

Let’s sort our dataframe by lowest Hours and Department.

In [ ]:
columns = ['Department', 'Hours']
order = [False, True]
courses.sort_values(by=columns, ascending=order)

In [26]:
us_babies = pd.read_csv("us_baby_names.csv")

In [27]:
us_babies

Id       Name  Year Gender  Count
0              1       Mary  1880      F   7065
1              2       Anna  1880      F   2604
2              3       Emma  1880      F   2003
3              4  Elizabeth  1880      F   1939
4              5     Minnie  1880      F   1746
...          ...        ...   ...    ...    ...
1825428  1825429     Zykeem  2014      M      5
1825429  1825430     Zymeer  2014      M      5
1825430  1825431    Zymiere  2014      M      5
1825431  1825432      Zyran  2014      M      5
1825432  1825433      Zyrin  2014      M      5

[1825433 rows x 5 columns]

#### Question : what were the 5 most popular baby names in 2014 in the united states?

Answer:
    1. slice out rows for 2014
    2. Sort rows in decending order by count
    3. Get first five rows

In [ ]:
us_babies['Year']

In [ ]:
us_babies['Year'] == 2014

In [ ]:
us_babies.loc[us_babies['Year'] == 2014, :]

In [ ]:
us_babies_2014 = us_babies.loc[us_babies['Year'] == 2014, :]

In [ ]:
us_babies_2014

In [ ]:
sorted_us_2014 = us_babies_2014.sort_values('Count', ascending=False)

In [ ]:
sorted_us_2014

In [ ]:
sorted_us_2014.iloc[0:5]

In [ ]:
states_babies = pd.read_csv('state_baby_names.csv')

In [ ]:
states_babies

#### Questions : what were the 5 most popular baby names in California

Answer:
    1. slice out the rows for the year 2014
    2. Slice out the rows for the state California
    3. Sort the rows in decending order by Count
    4. Get the first five rows

In [ ]:
states_babies_2014 = states_babies.loc[states_babies['Year'] == 2014,:]

In [ ]:
ca_babies_2014 = states_babies_2014.loc[states_babies_2014['State'] == 'CA',:]

In [ ]:
sorted_ca_babies_2014 = ca_babies_2014.sort_values('Count', ascending = False)

In [ ]:
sorted_ca_babies_2014.iloc[0:5]

#### Question : what were the most popular Male and Female baby names in California

Answer:
    1. Slice out the rows for California
    2. Group resulting DataFrame by 'Year' and 'Gender'
    3. Compute the most popular name for each Group

In [ ]:
ca_states_babies = states_babies.loc[states_babies['State'] == 'CA',:]

In [ ]:
ca_states_babies

In [ ]:
def popular(s):
    """Receives s, a Panda series, contaning baby names in order of highest count to lowest count.
    Retuns the most popular name in s."""
    return s.iloc[0]

In [ ]:
ca_grouped = ca_states_babies.sort_values('Count', ascending = False).groupby(['Year', 'Gender']).agg(popular)

In [ ]:
ca_grouped.sort_values('Year', ascending = False)

##### Question: How frequent your baby name occurs across the year in US among baby names

Answer:
    1. slice out the rows containing my first name
    2. Create a Horizontal bar plot for occurence of my name over the years

In [ ]:
us_nisha = us_babies.loc[us_babies['Name'] == 'Ajit', :]

In [ ]:
us_nisha

In [ ]:
us_nisha.plot.barh(x = 'Year', y = 'Count')

In [ ]:
crime = pd.read_csv('crime_boston.csv')

In [ ]:
crime

In [ ]:
crime.isnull() # to return the True for null values in Data Frame

In [ ]:
crime.isnull().any(axis = 1)  # Output is Panda series that contains boolean. It represents each row with boolean indicating does that row has missing value. True means yes it had and False mean no missing data

In [ ]:
rows_with_missing_vals = crime.isnull().any(axis = 1)
crime[rows_with_missing_vals]

In [ ]:
crime_cleaned =  crime.drop(columns = ['YEAR','MONTH','HOUR']) # Drop the irrelavent columns from table

In [ ]:
crime_cleaned['OFFENSE_CODE_GROUP'].unique()

In [ ]:
crime_cleaned['DAY_OF_WEEK'].unique()

In [ ]:
crime_cleaned = crime_cleaned.drop(columns = 'Location')

#### Qualitative Data Virtualization

In [28]:
import matplotlib.pyplot as plt
import seaborn as sns

ModuleNotFoundError: No module named 'seaborn'

In [ ]:
listings = pd.read_csv('AB_NYC_2019.csv')

In [ ]:
listings

In [ ]:
sns.countplot(x = 'neighbourhood_group' , data = listings)
plt.show()

In [ ]:
sns.barplot(x = 'neighbourhood_group', y = 'price', data = listings)
plt.show()

In [ ]:
sns.barplot(x = 'neighbourhood_group', y = 'price', data = listings, ci = False)
plt.show()

#### Quantitative Data Virtualization

In [ ]:
plt.hist(listings['price'])
plt.xlabel('price (in US dollars)')
plt.show()

In [ ]:
plt.hist(listings['price'], bins = np.arange(0, 1100, 40))
plt.xlabel('price (in US dollars)')
plt.show()

In [ ]:
plt.scatter(x = listings['price'], y = listings['number_of_reviews'])
plt.xlabel('price')
plt.ylabel('number of reviews')
plt.show()

In [ ]:
plt.scatter(x = listings['price'], y = listings['number_of_reviews'])
plt.xlabel('price')
plt.ylabel('number of reviews')
plt.xlim(0, 1100)
plt.show()

In [ ]:
plt.scatter(x = listings['price'], y = listings['number_of_reviews'], s = 4)
plt.xlabel('price')
plt.ylabel('number of reviews')
plt.xlim(0, 1100)
plt.show()

***********************************************************************************************

An introduction to seaborn¶
Seaborn is a library for making statistical graphics in Python. It is built on top of matplotlib and closely integrated with pandas data structures.

Here is some of the functionality that seaborn offers:

A dataset-oriented API for examining relationships between multiple variables

Specialized support for using categorical variables to show observations or aggregate statistics

Options for visualizing univariate or bivariate distributions and for comparing them between subsets of data

Automatic estimation and plotting of linear regression models for different kinds dependent variables

Convenient views onto the overall structure of complex datasets

High-level abstractions for structuring multi-plot grids that let you easily build complex visualizations

Concise control over matplotlib figure styling with several built-in themes

Tools for choosing color palettes that faithfully reveal patterns in your data

Seaborn aims to make visualization a central part of exploring and understanding data. Its dataset-oriented plotting functions operate on dataframes and arrays containing whole datasets and internally perform the necessary semantic mapping and statistical aggregation to produce informative plots.

In [ ]:
fmri = sns.load_dataset("fmri")
fmri.head()

In [ ]:
sns.set()
tips = sns.load_dataset("tips")
sns.relplot(x="total_bill", y="tip", col="time",
            hue="smoker", style="smoker", size="size",
            data=tips);